(() => {
  const D = window.TRIP;
  const $ = (s, el=document) => el.querySelector(s);
  const esc = s => String(s).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const place = id => D.places[id];
  const amap = p => `https://uri.amap.com/search?keyword=${encodeURIComponent(p.amap)}&city=442000`;
  const baidu = p => `https://api.map.baidu.com/geocoder?address=${encodeURIComponent(p.address)}&output=html`;
  const apple = p => `https://maps.apple.com/?q=${encodeURIComponent(p.name)}`;
  function nav(p){return `<div class="nav-actions"><a href="${amap(p)}" target="_blank" rel="noopener">高德导航</a><a href="${baidu(p)}" target="_blank" rel="noopener">百度地图</a><a href="${apple(p)}" target="_blank" rel="noopener">Apple 地图</a></div>`}
  $('#stats').innerHTML = [['出行','广州南 ↔ 中山北'],['住宿','石岐 / 兴中广场'],['步行','约 6—8 km / 两日'],['适合','情侣慢游 + 夜景']].map(x=>`<div class="stat"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');
  $('#transportList').innerHTML = D.transport.map(x=>`<article class="card"><span class="pill">${x.tag}</span><h3>${x.title}</h3><p><b>${x.time}</b> · ${x.price}</p><p>${x.why}</p><p class="muted">${x.action}</p><a class="cta" href="https://www.12306.cn/index/" target="_blank" rel="noopener">去 12306 查当日班次 →</a></article>`).join('');
  $('#timeline').innerHTML = ['day1','day2'].map((day,i)=>`<div class="day-title">DAY ${i+1} · ${i===0?'石岐老城、岐江、夜景':'轻装补拍、午餐、回广州'}</div><div class="timeline">${D.timeline.filter(x=>x.day===day).map((x,n)=>{const p=place(x.place);return `<details class="card stop" data-tags="${x.type.join(' ')}" id="${x.id}" ${n===0&&i===0?'open':''}><summary><div><div class="time">${x.time}</div><div class="mini">${p.emoji} ${p.short}</div></div><div><b>${x.title}</b><div class="mini">${p.name}</div></div><span class="chev">＋</span></summary><div class="timeline-body"><p>${x.detail}</p><div class="route-info"><span><b>怎么去：</b>${x.route}</span><span class="cost">${x.cost}</span></div>${nav(p)}</div></details>`}).join('')}</div>`).join('');
  const routeNodes = ['gzSouth','zsNorth','hotel','museum','sunwen','qijiang','xingzhong'];
  $('#routeFlow').innerHTML = routeNodes.map((id,i)=>`<div class="route-node">${place(id).emoji}<br>${place(id).short}</div>${i<routeNodes.length-1?'<div class="route-arrow">→</div>':''}`).join('');
  const pts = ['zsNorth','hotel','museum','sunwen','qijiang','xingzhong','pigeon','minxin'];
  $('#map').insertAdjacentHTML('beforeend', pts.map(id=>{const p=place(id), c=p.emoji==='🟡'?'food':p.emoji==='🔵'?'hotel':id==='zsNorth'?'start':'';return `<button class="marker ${c}" data-place="${id}" style="left:${p.x}%;top:${p.y}%" aria-label="${p.name}"><i><span>${p.emoji}</span></i><small>${p.short}</small></button>`}).join(''));
  $('#map').insertAdjacentHTML('beforeend', `<svg class="route-svg" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="27,29 61,41 48,42 51,48 38,59 68,61" fill="none" stroke="#c89d4b" stroke-width=".65" stroke-dasharray="1.7 1.3"/><polyline points="27,29 61,41 68,61" fill="none" stroke="#1e5544" stroke-width=".7" opacity=".85"/></svg><div class="map-legend">🟢 车站　🔴 景点　🟡 美食　🔵 酒店<br><span style="color:#1e5544">━━</span> Day 1 / <span style="color:#c89d4b">┄┄</span> Day 2 补拍回程</div>`);
  function showPlace(id){const p=place(id);$('#mapInfo').innerHTML=`<span class="pill">${p.emoji} 地图标记</span><h3>${p.name}</h3><p>${p.address}</p><p class="map-panel-placeholder">此图是无 API Key 的离线路线示意，非比例尺导航。点击下方按钮打开实时地图、步行/公交/网约车路线。</p>${nav(p)}`;}
  $('#map').addEventListener('click',e=>{const b=e.target.closest('.marker');if(b)showPlace(b.dataset.place)});showPlace('xingzhong');
  $('#photos').innerHTML=D.photoSpots.map(x=>`<article class="card photo-card" data-tags="photo couple"><div class="photo-art" aria-label="${esc(x.place)} 氛围示意图，不使用博主原图"></div><div class="photo-content"><span class="pill">可发朋友圈</span><h3>${x.place}</h3><p><b>时间/光：</b>${x.time}；${x.light}</p><p><b>站位：</b>${x.shot}</p><p><b>镜头：</b>${x.lens}</p><p><b>手机：</b>${x.phone}</p><p><b>动作：</b>${x.pose}</p><p><b>避人：</b>${x.avoid}</p><a class="source-link" href="${x.url}" target="_blank" rel="noopener">来源：${x.source} ↗</a></div></article>`).join('');
  $('#hotels').innerHTML=D.hotels.map(x=>`<article class="card hotel-card ${x.recommended?'recommended':''}" data-tags="hotel couple"><span class="pill">${x.tier}</span><h3>${x.name}</h3><div class="hotel-meta">${x.area} · ${x.price}</div><ul><li><b>走路：</b>${x.walk}</li><li><b>去中山北：</b>${x.station}</li><li><b>房间：</b>${x.room}</li><li><b>优点：</b>${x.good}</li><li><b>注意：</b>${x.watch}</li></ul><a class="cta" href="https://hotels.ctrip.com/" target="_blank" rel="noopener">查实时房价与近期评价 →</a></article>`).join('');
  $('#foods').innerHTML=D.food.map(x=>`<article class="card food-card" data-tags="food"><span class="pill">${x.meal}</span><h3>${x.name}</h3><div class="hotel-meta">${x.near} · ${x.price}</div><ul><li><b>推荐：</b>${x.order}</li><li><b>少点：</b>${x.skip}</li><li><b>排队：</b>${x.queue}</li><li><b>是否专程：</b>${x.worth}</li></ul></article>`).join('');
  $('#sources').innerHTML=D.sources.map(x=>`<article class="card source-card"><span class="kind">${x.kind}</span><h3>${x.title}</h3><p class="muted">${x.note}</p><a href="${x.url}" target="_blank" rel="noopener">打开原始来源 ↗</a></article>`).join('');
  $('#filterBar').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;[...$('#filterBar').children].forEach(x=>x.classList.toggle('active',x===b));const tag=b.dataset.filter;document.querySelectorAll('[data-tags]').forEach(el=>el.classList.toggle('hidden',tag!=='all'&&!el.dataset.tags.split(' ').includes(tag)));});
  let n=0;const stops=[...document.querySelectorAll('.stop')];$('#taskMode').addEventListener('click',()=>{stops.forEach(s=>s.classList.remove('active-stop'));const s=stops[n++%stops.length];s.open=true;s.classList.add('active-stop');s.scrollIntoView({behavior:'smooth',block:'center'});});
  $('#year').textContent=new Date().getFullYear();
})();
